language: node_js

node_js:
  - "4"

addons:
  apt:
    packages:
      - oracle-java8-installer
  
env:
  global:
    - GH_REF: github.com/MARIE-js/MARIE.js.git
    - secure: "Iw4dDOh6Il4wh955AWZB+S/wL3s6quwwT10KZytBC8Wyz9FjvZK2jZ0wkXLV5JN9wHQUt7Fx2rbRwQlPRsspSpIta/Vz+dywi3jMXY0eOCTD6T7VFtkJtSng6t21XPFM217DCKOfih16SFTFwFH1r4cEtdRpcJkfKau78ynCD+h+hI1VKnyIfLIR3WNB9FSTl8OcY2axuStyncvFvMqt8HOl2L5V2chAhNP3rMJy3hRmAU3Dz90GDgVYYdquHA83cKQpbFY3TtreTjr09onkUL7q/SlWzO4+PicF+eanUKs+uGhxhI5ujiYWJI9hevGKUJPP9IMbEeB00vMllw6jz5BDOIE6uC6ODNARbrgsTldhBoglWKxBKhDIMzeMTIjD03Jm2RoOn2NSoWvKstaVDlHXOUvJqPDc8SyUJEtlPfPa2e0buQ/G8V7rcDQy4p6un3Gf5tzx6ZJiw1Btb2TtP+gWOMI+8gznRsWDiVybB782olei+P430u99NB13SBHdz5z+ZdxTLhQtHrdM991evz70JKIDlaS9byeCvQxZPXyf58HPB+EwsanL4NO2Bm3mYwJk/ssoKbnGHtSJxNp4IVqgHw7KT74/EOv7qmkhItrqr/2i75L0Rz0dTBc0NX9EpvzB9kRJNi2PtitsjsN7X9MAR5agWEAXs1r2EoROHAo="

install:
  - npm install -g grunt-cli
  - npm install

before_script:
  - export PATH=/usr/lib/jvm/java-8-oracle/bin:$PATH

script:
  - grunt test
  - grunt build

after_success:
  - '[ "${TRAVIS_BRANCH}" = "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash ./deploy.sh'
